"""
Django settings for lunchnetsale project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
import dj_database_url
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# ▼ ユーティリティ：カンマ区切り環境変数を配列へ
def csv_env(name: str, default: str = ""):
    return [s.strip() for s in os.environ.get(name, default).split(",") if s.strip()]

# --- 環境判定 ---
# Heroku は dyno 上で必ず DYNO 環境変数を立てる。DJANGO_ENV を production に
# し忘れる/タイポしても本番安全側（DEBUG=False・secure cookie 等）に倒すため、
# 「DJANGO_ENV=production」または「Heroku dyno 上」を本番とみなす（フェイルセーフ）。
DJANGO_ENV = os.environ.get('DJANGO_ENV', 'development')
IS_PRODUCTION = DJANGO_ENV == 'production' or bool(os.environ.get('DYNO'))

# --- 本番フラグ ---
# 本番では DEBUG を常に False に固定（env で DEBUG=True にしても無効）。
# 開発時のみ DEBUG 環境変数で上書き可能。
if IS_PRODUCTION:
    DEBUG = False
else:
    DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# --- SECRET_KEY ---
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY が未設定です。.env または Heroku Config Vars に設定してください。"
    )
# 本番では Django の自動生成キー（django-insecure- 接頭辞）での起動を拒否する。
# 弱い開発用キーのまま本番デプロイすると署名系のセキュリティが破られるため。
if IS_PRODUCTION and SECRET_KEY.startswith("django-insecure-"):
    raise ImproperlyConfigured(
        "本番で開発用の脆弱な SECRET_KEY が使われています。"
        "Heroku Config Vars に十分に長くランダムな SECRET_KEY を設定してください。"
    )

# --- Host/CSRF 設定 ---
ALLOWED_HOSTS = csv_env("ALLOWED_HOSTS", "localhost,127.0.0.1")
CSRF_TRUSTED_ORIGINS = csv_env("CSRF_TRUSTED_ORIGINS")

# --- LINE予約（LIFF・案L）設定 ---
# LIFF ID はフロントに露出する公開値。チャネルシークレット/アクセストークン等の機密は置かない。
LIFF_ID = os.environ.get("LIFF_ID", "2010353511-5kQfbV06")
# 顧客がQRなしで再注文するための「予約リンク」＝LIFF URL（LINEで開くと予約フォームになる）。
# 確定通知・控え・履歴に載せる。テスト中は単一拠点のLIFFに解決。複数拠点化は将来 env で上書き。
LIFF_RESERVE_URL = os.environ.get("LIFF_RESERVE_URL") or f"https://liff.line.me/{LIFF_ID}"
# 登録済みテスト客にだけ出す「予約リッチメニュー」のID（setup_reservation_richmenu で採番）。
LINE_RESERVE_RICHMENU_ID = os.environ.get("LINE_RESERVE_RICHMENU_ID", "")
# ※ push通知の送信元 LINE_CHANNEL_ACCESS_TOKEN は下の「LINE Bot 設定」で定義（重複定義を排除）。
# 予約に LINE 連携（友だち必須＋userId本人識別）を要求するか。
# 本番=必須。ローカル開発のみ False で、LINE未連携の仮会員フォールバックを許可（動作確認用）。
RESERVE_REQUIRE_LINE = (
    os.environ.get("RESERVE_REQUIRE_LINE", "True" if IS_PRODUCTION else "False") == "True"
)

# --- スタンプカード（来店計測）設定 ---
# 予約と同じ LIFF / 本人識別の仕組みを共用する（同一公式アカウント・同一 LIFF_ID）。
# LIFF のエンドポイントは /stamp/ も含む必要がある（/reserve/ と同じドメイン直下）。
# スタンプにLINE連携（userId本人識別）を要求するか。未設定なら予約と同じ既定に従う。
STAMP_REQUIRE_LINE = (
    os.environ.get("STAMP_REQUIRE_LINE", "True" if IS_PRODUCTION else "False") == "True"
)
# スタンプQRに埋め込む LIFF。通常カメラで読んでも LINE アプリ内で開くために、QRは
# 素のWeb URLではなく liff.line.me/<LIFF_ID>/stamp/<token>/ を指す（LINEのショップQRと同じ）。
# 既定は予約と同じ LIFF_ID を流用。専用LIFFを切るときだけ STAMP_LIFF_ID を上書きする。
# ※LINE Developers 側で、この LIFF のエンドポイントURLが /stamp/ を含む必要がある（ドメイン直下推奨）。
STAMP_LIFF_ID = os.environ.get("STAMP_LIFF_ID", LIFF_ID)

# スタンプ利用者専用リッチメニュー（per-user 配信）。setup_stamp_richmenu で作成→ここに設定。
# デフォルト（全友だち）には設定しない＝既存メニューのまま。初回スタンプ時にこのIDを本人へリンク。
LINE_STAMP_RICHMENU_ID = os.environ.get("LINE_STAMP_RICHMENU_ID", "")
# 初回スタンプ時に自動でスタンプ用リッチメニューを本人へ割り当てるか。
STAMP_RICHMENU_AUTO_ASSIGN = os.environ.get("STAMP_RICHMENU_AUTO_ASSIGN", "True") == "True"

# --- Heroku で HTTPS を正しく認識させる（超重要） ---
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# --- HTTP→HTTPS を強制（開発時は無効） ---
SECURE_SSL_REDIRECT = IS_PRODUCTION

# --- HSTS（本番のみ） ---
SECURE_HSTS_SECONDS = 31536000 if IS_PRODUCTION else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False

# --- Cookie を HTTPS 限定に（本番のみ） ---
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION

# --- CSRF 失敗時のカスタムビュー ---
CSRF_FAILURE_VIEW = 'lunchnetsale.views.csrf_failure_view'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sales',
    'shifts',
    'orders',
    'quest',
    'attendance',
    'reservations',
    'stamps',
    'lunchnetsale',
    'django.contrib.humanize',
    'axes',
    'whitenoise.runserver_nostatic',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(hours=1)
AXES_LOCK_OUT_AT_FAILURE = True
AXES_RESET_ON_SUCCESS = True
AXES_LOCK_OUT_URL = '/locked_out/'

# 静的ファイル: 本番のみWhiteNoise圧縮、開発時はDjangoデフォルト
if IS_PRODUCTION:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
else:
    WHITENOISE_USE_FINDERS = True

ROOT_URLCONF = 'lunchnetsale.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'lunchnetsale.context_processors.unread_message_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'lunchnetsale.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{os.path.join(os.path.dirname(__file__), "db.sqlite3")}',
        conn_max_age=600,
        ssl_require=IS_PRODUCTION
    )
}


LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/login/'

# セッションタイムアウト設定
# ここはデフォルト値（フォールバック）。実際の有効期限はログイン時に
# ロール別で上書きしている（lunchnetsale/views.py login_view: 管理者24時間 / 一般30日）。
# SESSION_SAVE_EVERY_REQUEST=True なので「最終操作からの放置時間」でカウント（スライド式）。
SESSION_COOKIE_AGE = 24 * 60 * 60
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'axes.backends.AxesStandaloneBackend',
]



# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- メール送信設定 (Gmail App Password) ---
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# --- LINE Bot 設定 ---
LINE_CHANNEL_ACCESS_TOKEN = os.environ.get('LINE_CHANNEL_ACCESS_TOKEN', '')
LINE_CHANNEL_SECRET = os.environ.get('LINE_CHANNEL_SECRET', '')
LINE_BOT_BASIC_ID = os.environ.get('LINE_BOT_BASIC_ID', '')  # 例: @abc12345

# --- LOGGING ---
# print() デバッグ文を廃し、出力をログに一元化する（C8）。
# 本番=INFO（debugログは出さない）／開発=DEBUG。Herokuはstdoutをログ収集するためconsoleのみで足りる。
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "[{levelname}] {asctime} {name}: {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "simple"},
    },
    "root": {"handlers": ["console"], "level": "INFO" if IS_PRODUCTION else "DEBUG"},
    "loggers": {
        "django": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}
