"""
Django settings for lunchnetsale project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

import os

from datetime import timedelta
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

CSRF_COOKIE_SECURE = True  # HTTPS を使う場合は True


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--+q6!izt3($eu-q*8)3dgu$#zp6rj)n$(jkyi^-wxo-v%$l1(!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


#ALLOWED_HOSTS = ['lunchnetsalessystem-c7bbb644044e.herokuapp.com', 'localhost']
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'lunchnetsalessystem-c7bbb644044e.herokuapp.com,localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sales',
    'lunchnetsale',
    'django.contrib.humanize',
    'axes',
    'whitenoise.runserver_nostatic',  # whitenoiseを追加
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # これが正しい順番
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

AXES_FAILURE_LIMIT = 5  # 最大5回の失敗を許可
AXES_COOLOFF_TIME = timedelta(hours=1)  # 1時間後に再試行可能
AXES_LOCK_OUT_AT_FAILURE = True  # 試行失敗後にアカウントをロック
AXES_RESET_ON_SUCCESS = True  # 成功ログインでカウントをリセット
AXES_LOCK_OUT_URL = '/locked_out/'  # カスタムのロックアウトページのURL

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'lunchnetsale.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lunchnetsale.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# デフォルトではSQLiteを使用し、環境変数が設定されていればそれを利用
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{os.path.join(os.path.dirname(__file__), "db.sqlite3")}',
        conn_max_age=600,
        ssl_require=os.getenv('DJANGO_ENV') == 'production'  # 本番環境でのみSSLを強制
    )
}


LOGIN_URL = '/login/'  # 未ログインのユーザーがアクセスしようとしたときにリダイレクトされるログインページのURL名
LOGOUT_REDIRECT_URL = '/login/'  # ログアウト後にリダイレクトされるURL名

# セッションタイムアウト設定（例: 1ヶ月）
SESSION_COOKIE_AGE = 30 * 24 * 60 * 60  # 秒単位で指定（1ヶ月 = 2592000秒）

# ブラウザを閉じたらセッションを終了する設定
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# セッションがアクティブな間でも、非アクティブ時間でセッションを終了する設定
SESSION_SAVE_EVERY_REQUEST = False


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'axes.backends.AxesStandaloneBackend',  # django-axes の新しいバックエンド
]



# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# lunchnetsale/settings.py

STATIC_URL = '/static/'
# settings.py に追加
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')




# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
