# Generated by Django 5.1.1 on 2026-06-28 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0003_reservation_uniq_active_reservation_per_member_day'),
        ('sales', '0075_stamp_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_pt', models.PositiveIntegerField(help_text='このポイント数に到達した瞬間に特典を発行する（例：5/10/20）。', unique=True, verbose_name='到達ポイント')),
                ('kind', models.CharField(choices=[('discount', '割引'), ('free', '弁当無料')], default='discount', max_length=10, verbose_name='種類')),
                ('label', models.CharField(help_text='お客様に表示する文言（例：50円引き／弁当1個無料）。', max_length=60, verbose_name='特典名')),
                ('discount_yen', models.PositiveIntegerField(default=0, help_text='割引特典のときの引く金額。弁当無料のときは0。', verbose_name='割引額（円）')),
                ('benefit_cost', models.PositiveIntegerField(default=0, help_text='この特典1回あたりの想定コスト（損益集計用）。割引＝割引額／弁当無料＝弁当原価。', verbose_name='基準コスト（円）')),
                ('is_cap', models.BooleanField(default=False, help_text='ON の段階に到達したらそのサイクルは満了（以降スタンプを押さない）。20ptに付ける。', verbose_name='打ち止め段階')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '特典段階',
                'verbose_name_plural': '特典段階',
                'ordering': ['threshold_pt'],
            },
        ),
        migrations.CreateModel(
            name='StampCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateField(db_index=True, verbose_name='初回利用日')),
                ('expires_on', models.DateField(db_index=True, verbose_name='有効期限')),
                ('stamp_count', models.PositiveIntegerField(default=0, verbose_name='スタンプ数')),
                ('status', models.CharField(choices=[('active', '利用中'), ('completed', '満了（打ち止め）'), ('expired', '期限切れ')], db_index=True, default='active', max_length=10, verbose_name='状態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_cards', to='reservations.linemember', verbose_name='会員')),
            ],
            options={
                'verbose_name': 'スタンプカード',
                'verbose_name_plural': 'スタンプカード',
                'ordering': ['-started_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_pt', models.PositiveIntegerField(verbose_name='到達ポイント')),
                ('kind', models.CharField(max_length=10, verbose_name='種類')),
                ('label', models.CharField(max_length=60, verbose_name='特典名')),
                ('benefit_cost', models.PositiveIntegerField(default=0, verbose_name='基準コスト（円）')),
                ('issued_at', models.DateTimeField(verbose_name='発行日時')),
                ('expires_on', models.DateField(verbose_name='有効期限')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用日時')),
                ('status', models.CharField(choices=[('issued', '獲得済'), ('used', '使用済'), ('expired', '期限切れ')], db_index=True, default='issued', max_length=10, verbose_name='状態')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rewards', to='stamps.rewardtier', verbose_name='特典段階')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='stamps.stampcard', verbose_name='カード')),
            ],
            options={
                'verbose_name': '特典',
                'verbose_name_plural': '特典',
                'ordering': ['threshold_pt'],
                'constraints': [models.UniqueConstraint(fields=('card', 'threshold_pt'), name='uniq_reward_per_card_per_tier')],
            },
        ),
        migrations.CreateModel(
            name='StampLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamped_on', models.DateField(db_index=True, verbose_name='来店日')),
                ('stamped_at', models.DateTimeField(verbose_name='来店日時')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='stamps.stampcard', verbose_name='カード')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stamp_logs', to='sales.saleslocation', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '来店ログ',
                'verbose_name_plural': '来店ログ',
                'ordering': ['-stamped_at'],
                'indexes': [models.Index(fields=['location', 'stamped_on'], name='stamps_stam_locatio_1dfad2_idx')],
                'constraints': [models.UniqueConstraint(fields=('card', 'stamped_on'), name='uniq_stamp_per_card_per_day')],
            },
        ),
    ]
