# Generated by Django 5.1.1 on 2026-06-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0003_obento_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardtier',
            name='benefit_cost',
            field=models.PositiveIntegerField(default=0, help_text='この特典1回あたりの想定コスト（損益集計用）。割引＝割引額／お弁当無料＝お弁当原価。', verbose_name='基準コスト（円）'),
        ),
        migrations.AlterField(
            model_name='rewardtier',
            name='discount_yen',
            field=models.PositiveIntegerField(default=0, help_text='割引特典のときの引く金額。お弁当無料のときは0。', verbose_name='割引額（円）'),
        ),
        migrations.AlterField(
            model_name='rewardtier',
            name='kind',
            field=models.CharField(choices=[('discount', '割引'), ('free', 'お弁当無料')], default='discount', max_length=10, verbose_name='種類'),
        ),
        migrations.AlterField(
            model_name='rewardtier',
            name='label',
            field=models.CharField(help_text='お客様に表示する文言（例：50円引き／お弁当1個無料）。', max_length=60, verbose_name='特典名'),
        ),
    ]
