# Generated by Django 5.1.1 on 2026-06-30 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_uniq_active_reservation_per_member_day'),
        ('stamps', '0005_reward_valid_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichMenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rich_menu_id', models.CharField(blank=True, max_length=64, verbose_name='リッチメニューID')),
                ('status', models.CharField(choices=[('linked', '適用中'), ('unlinked', '解除'), ('failed', '失敗')], db_index=True, default='failed', max_length=10, verbose_name='状態')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='詳細/エラー')),
                ('linked_at', models.DateTimeField(blank=True, null=True, verbose_name='適用日時')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_richmenu_link', to='reservations.linemember', verbose_name='会員')),
            ],
            options={
                'verbose_name': 'リッチメニュー割当て',
                'verbose_name_plural': 'リッチメニュー割当て',
                'ordering': ['-updated_at'],
            },
        ),
    ]
