# Generated by Django 5.1.1 on 2026-06-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0006_richmenulink'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('stamp', 'スタンプ利用者')], default='stamp', max_length=20, unique=True, verbose_name='用途（セグメント）')),
                ('name', models.CharField(default='スタンプ利用者メニュー', max_length=80, verbose_name='名前')),
                ('image_data', models.BinaryField(blank=True, null=True, verbose_name='画像(PNG)')),
                ('image_width', models.PositiveIntegerField(default=2500)),
                ('image_height', models.PositiveIntegerField(default=1686)),
                ('areas', models.JSONField(default=list, verbose_name='タップ領域')),
                ('chat_bar_text', models.CharField(default='メニュー', max_length=14, verbose_name='メニューバー文言')),
                ('line_rich_menu_id', models.CharField(blank=True, max_length=64, verbose_name='LINEリッチメニューID')),
                ('registered_at', models.DateTimeField(blank=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'リッチメニュー',
                'verbose_name_plural': 'リッチメニュー',
            },
        ),
    ]
