# Generated by Django 5.1.1 on 2026-07-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0007_richmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='StampConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_validity_days', models.PositiveIntegerField(default=30, help_text='初回スタンプから何日でカードが切り替わるか。', verbose_name='カードの有効日数')),
                ('reward_validity_days', models.PositiveIntegerField(default=30, help_text='特典を獲得した日から何日使えるか（カードとは独立）。', verbose_name='クーポンの有効日数')),
                ('reward_starts_next_day', models.BooleanField(default=True, help_text='ON＝獲得した来店では使えず次回来店から（10回購入で1個無料を守る）。OFF＝当日から使える。', verbose_name='クーポンは翌日から')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'スタンプ運用設定',
                'verbose_name_plural': 'スタンプ運用設定',
            },
        ),
    ]
