# Generated by Django 5.1.1 on 2026-07-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0008_stampconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampconfig',
            name='rain_bonus_date',
            field=models.DateField(blank=True, help_text='この日付の来店はスタンプ2倍。雨の朝にスタッフが当日をセット。翌日は自動でOFF（押し忘れ防止）。', null=True, verbose_name='雨の日ボーナス対象日'),
        ),
        migrations.AddField(
            model_name='stampconfig',
            name='streak_bonus_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='何日連続の節目で2倍にするか。3なら3・6・9日目…が2倍。', verbose_name='連続来店の節目（日）'),
        ),
        migrations.AddField(
            model_name='stampconfig',
            name='streak_bonus_enabled',
            field=models.BooleanField(default=True, help_text='ON＝連続来店の節目でスタンプ2倍。', verbose_name='連続来店ボーナス'),
        ),
        migrations.AddField(
            model_name='stamplog',
            name='bonus_reason',
            field=models.CharField(blank=True, choices=[('rain', '雨の日'), ('streak', '連続来店')], default='', help_text='2倍になった要因（雨の日／連続来店）。通常来店は空。集計・検証用。', max_length=10, verbose_name='2倍の理由'),
        ),
        migrations.AddField(
            model_name='stamplog',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, help_text='この来店で押したスタンプ数。通常1、2倍イベント該当日は2（打ち止め手前で1になることもある）。', verbose_name='付与pt'),
        ),
    ]
