# Generated by Django 5.1.1 on 2026-07-19 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_uniq_active_reservation_per_member_day'),
        ('stamps', '0009_stampconfig_rain_bonus_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendTagConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_within_days', models.PositiveIntegerField(default=14, help_text='登録からこの日数以内、かつ来店が少ない人を「新規」にする。', verbose_name='新規：登録からの日数')),
                ('new_max_visits', models.PositiveIntegerField(default=2, help_text='来店がこの回数以下なら「新規」の対象（超えたらリピーター等に切り替わる）。', verbose_name='新規：来店回数の上限')),
                ('repeater_min_visits', models.PositiveIntegerField(default=1, verbose_name='リピーター：来店回数の下限')),
                ('regular_min_visits', models.PositiveIntegerField(default=5, verbose_name='常連：来店回数の下限')),
                ('heavy_min_visits', models.PositiveIntegerField(default=10, verbose_name='ヘビー：来店回数の下限')),
                ('dormant_days', models.PositiveIntegerField(default=21, help_text='最終来店からこの日数以上あいたら「離反ぎみ」にする。', verbose_name='離反ぎみ：最終来店からの日数')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '友だちタグ設定',
                'verbose_name_plural': '友だちタグ設定',
            },
        ),
        migrations.CreateModel(
            name='MemberTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='タグ名')),
                ('color', models.CharField(choices=[('blue', '青'), ('green', '緑'), ('orange', 'オレンジ'), ('red', '赤'), ('purple', '紫'), ('gray', 'グレー')], default='blue', max_length=10, verbose_name='色')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '手動タグ',
                'verbose_name_plural': '手動タグ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MemberTagLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='reservations.linemember', verbose_name='会員')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='stamps.membertag', verbose_name='手動タグ')),
            ],
            options={
                'verbose_name': '手動タグ割当て',
                'verbose_name_plural': '手動タグ割当て',
                'ordering': ['tag__order', 'tag_id'],
                'constraints': [models.UniqueConstraint(fields=('member', 'tag'), name='uniq_member_tag')],
            },
        ),
    ]
