# Generated by Django 5.1.1 on 2026-07-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0010_friendtagconfig_membertag_membertaglink'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendInsightSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='集計日')),
                ('status', models.CharField(default='ready', max_length=16, verbose_name='集計状態')),
                ('followers', models.PositiveIntegerField(default=0, verbose_name='累計友だち追加')),
                ('targeted_reaches', models.PositiveIntegerField(default=0, verbose_name='実質有効友だち')),
                ('blocks', models.PositiveIntegerField(default=0, verbose_name='累計ブロック')),
                ('fetched_at', models.DateTimeField(verbose_name='取得日時')),
            ],
            options={
                'verbose_name': '友だち統計スナップショット',
                'verbose_name_plural': '友だち統計スナップショット',
                'ordering': ['-date'],
            },
        ),
    ]
