# Generated by Django 5.1.1 on 2026-08-12 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_uniq_active_reservation_per_member_day'),
        ('stamps', '0011_friendinsightsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('welcome', 'お礼'), ('second_visit', '次回後押し'), ('winback', '離反フォロー')], max_length=20, unique=True, verbose_name='種類')),
                ('enabled', models.BooleanField(default=False, verbose_name='有効')),
                ('template', models.TextField(help_text='変数 {名前}{現在pt}{次の特典まで}{次の特典}{メニューリンク} が使える。', verbose_name='文面')),
                ('offset_days', models.PositiveSmallIntegerField(default=0, help_text='トリガー基準日からの経過日数（お礼=0/1、次回後押し=初回から◯日、離反=最終来店から◯日）。', verbose_name='日数')),
                ('holdout_pct', models.PositiveSmallIntegerField(default=20, help_text='この割合は送らず残す＝送った人との再来率比較に使う（0だと効果を測れない）。', verbose_name='対照群（％）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '配信シナリオ',
                'verbose_name_plural': '配信シナリオ',
            },
        ),
        migrations.AddField(
            model_name='stampconfig',
            name='menu_url',
            field=models.URLField(blank=True, help_text='配信文面の {メニューリンク} に差し込むURL（今週のメニュー等）。', verbose_name='メニューリンクURL'),
        ),
        migrations.CreateModel(
            name='FollowupSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('welcome', 'お礼'), ('second_visit', '次回後押し'), ('winback', '離反フォロー')], max_length=20, verbose_name='種類')),
                ('cycle_key', models.DateField(help_text='この配信機会を識別する基準日（お礼/次回後押し＝初回来店日、離反＝最終来店日）。重複防止に使う。', verbose_name='基準日')),
                ('decided_on', models.DateField(db_index=True, verbose_name='判定日')),
                ('status', models.CharField(choices=[('sent', '送信'), ('held_out', '対照（送らず）'), ('failed', '失敗')], db_index=True, default='sent', max_length=10, verbose_name='状態')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='送信日時')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='詳細/エラー')),
                ('revisited', models.BooleanField(default=False, verbose_name='配信後に再来')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_logs', to='reservations.linemember', verbose_name='会員')),
            ],
            options={
                'verbose_name': '配信ログ',
                'verbose_name_plural': '配信ログ',
                'ordering': ['-decided_on', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('member', 'kind', 'cycle_key'), name='uniq_followup_per_cycle')],
            },
        ),
    ]
