# Generated by Django 5.1.1 on 2026-06-09 11:09

import django.db.models.deletion
import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0072_reservation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(db_index=True, help_text='LIFFで自動取得した userId。本人識別・LINE紐付けのキー。', max_length=64, unique=True, verbose_name='LINEユーザーID')),
                ('name', models.CharField(help_text='受取時の呼び出し用。初回登録。', max_length=100, verbose_name='お名前')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LINE会員',
                'verbose_name_plural': 'LINE会員',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField(db_index=True, verbose_name='受取日')),
                ('status', models.CharField(choices=[('received', '受付済'), ('handed', '受渡済'), ('cancelled', 'キャンセル'), ('noshow', 'ノーショー')], db_index=True, default='received', max_length=10, verbose_name='状態')),
                ('reservation_number', models.CharField(default=reservations.models._generate_reservation_number, max_length=12, unique=True, verbose_name='予約番号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.linemember', verbose_name='会員')),
                ('sales_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='sales.saleslocation', verbose_name='受取拠点')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
                'ordering': ['-pickup_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='注文時点の商品名スナップショット。', max_length=255, verbose_name='商品名')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='個数（合計）')),
                ('quantity_large', models.PositiveIntegerField(default=0, verbose_name='大盛り数')),
                ('quantity_regular', models.PositiveIntegerField(default=0, verbose_name='普通盛り数')),
                ('quantity_small', models.PositiveIntegerField(default=0, verbose_name='小盛り数')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='単価（基本・盛り共通）')),
                ('large_surcharge', models.DecimalField(decimal_places=0, default=0, help_text='大盛り1個あたりの追加額（既定50・大盛りごはんProduct由来）。', max_digits=10, verbose_name='大盛り割増')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.product', verbose_name='商品')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservations.reservation', verbose_name='予約')),
            ],
            options={
                'verbose_name': '予約明細',
                'verbose_name_plural': '予約明細',
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['sales_location', 'pickup_date', 'status'], name='reservation_sales_l_83de94_idx'),
        ),
    ]
