# Generated by Django 5.1.1 on 2026-06-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_reminder_sent'),
        ('sales', '0072_reservation_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('received', 'handed'))), fields=('member', 'pickup_date'), name='uniq_active_reservation_per_member_day'),
        ),
    ]
