# Generated by Django 5.1.1 on 2026-09-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_uniq_active_reservation_per_member_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='linemember',
            name='block_checked_at',
            field=models.DateTimeField(blank=True, help_text='ブロック状態を最後にLINEへ照会した日時。未照会ならNone。', null=True, verbose_name='ブロック状態の最終確認'),
        ),
        migrations.AddField(
            model_name='linemember',
            name='blocked',
            field=models.BooleanField(db_index=True, default=False, help_text='LINEでこの公式アカウントをブロック中（プロフィールAPIで判定）。', verbose_name='ブロック中'),
        ),
    ]
