# Generated by Django 5.1.1 on 2026-02-16 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0055_saleslocation_priority_saleslocation_requires_drive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日付')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
            ],
            options={
                'verbose_name': '会社休日',
                'verbose_name_plural': '会社休日',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SchedulePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('submission_open_at', models.DateTimeField(verbose_name='提出受付開始')),
                ('submission_close_at', models.DateTimeField(verbose_name='提出締切')),
                ('status', models.CharField(choices=[('OPEN', '募集中'), ('REVIEW', '確認中'), ('FIXED', '確定'), ('PUBLISHED', '公開済')], default='OPEN', max_length=10, verbose_name='ステータス')),
            ],
            options={
                'verbose_name': '募集期間',
                'verbose_name_plural': '募集期間',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', '下書き'), ('SUBMITTED', '提出済'), ('RETURNED', '差戻')], default='DRAFT', max_length=10, verbose_name='ステータス')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提出日時')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='管理者メモ')),
                ('submitted_by_admin', models.BooleanField(default=False, verbose_name='管理者代理提出')),
                ('is_late_submission', models.BooleanField(default=False, verbose_name='締切後提出')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_submissions', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='shifts.scheduleperiod', verbose_name='期間')),
            ],
            options={
                'verbose_name': 'シフト希望提出',
                'verbose_name_plural': 'シフト希望提出',
                'unique_together': {('user', 'period')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_drive', models.BooleanField(default=False, verbose_name='運転可能')),
                ('work_pattern', models.CharField(choices=[('FULL', 'フルタイム'), ('PART', 'パートタイム')], default='FULL', max_length=4, verbose_name='勤務形態')),
                ('uses_app', models.BooleanField(default=True, verbose_name='アプリ利用')),
                ('min_shifts_per_week', models.PositiveIntegerField(default=0, verbose_name='最低出勤日数/週')),
                ('max_shifts_per_week', models.PositiveIntegerField(default=5, verbose_name='最大出勤日数/週')),
                ('fixed_weekdays', models.CharField(blank=True, default='', help_text='カンマ区切り: 0=月,1=火,...,6=日', max_length=50, verbose_name='固定出勤曜日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザープロフィール',
                'verbose_name_plural': 'ユーザープロフィール',
            },
        ),
        migrations.CreateModel(
            name='AvailabilityDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('availability', models.CharField(choices=[('WORK', '出勤'), ('OFF', '休み')], default='WORK', max_length=4, verbose_name='出勤/休み')),
                ('absence_category', models.CharField(blank=True, choices=[('PERSONAL', '私用'), ('SICK', '体調不良'), ('SUBSTITUTE', '代替出勤'), ('OTHER', 'その他')], default='', max_length=10, verbose_name='休みカテゴリ')),
                ('comment', models.CharField(blank=True, default='', max_length=200, verbose_name='コメント')),
                ('substitute_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_days', to=settings.AUTH_USER_MODEL, verbose_name='代替ユーザー')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='shifts.availabilitysubmission', verbose_name='提出')),
            ],
            options={
                'verbose_name': '日別シフト希望',
                'verbose_name_plural': '日別シフト希望',
                'ordering': ['date'],
                'unique_together': {('submission', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('status', models.CharField(choices=[('DRAFT', '仮'), ('CONFIRMED', '確定')], default='DRAFT', max_length=10, verbose_name='ステータス')),
                ('admin_note', models.CharField(blank=True, default='', max_length=200, verbose_name='管理者メモ')),
                ('sales_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='sales.saleslocation', verbose_name='売り場')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
            ],
            options={
                'verbose_name': 'シフト割当',
                'verbose_name_plural': 'シフト割当',
                'ordering': ['date', 'sales_location'],
                'unique_together': {('date', 'sales_location')},
            },
        ),
    ]
