# Generated by Django 5.1.1 on 2026-02-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitysubmission',
            name='remarks',
            field=models.TextField(blank=True, default='', verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='availabilitysubmission',
            name='status',
            field=models.CharField(choices=[('DRAFT', '下書き'), ('SUBMITTED', '提出済'), ('APPROVED', '承認済'), ('RETURNED', '差戻')], default='DRAFT', max_length=10, verbose_name='ステータス'),
        ),
    ]
