# Generated by Django 5.1.1 on 2026-02-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_availabilitysubmission_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='work_pattern',
            field=models.CharField(choices=[('FULL', 'フルタイム'), ('PART', 'パートタイム'), ('HELPER', '助っ人')], default='FULL', max_length=6, verbose_name='勤務形態'),
        ),
    ]
