# Generated by Django 5.1.1 on 2026-02-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_alter_userprofile_work_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok_threshold', models.PositiveIntegerField(default=2, verbose_name='OK上限（緑）')),
                ('warning_threshold', models.PositiveIntegerField(default=4, verbose_name='注意上限（黄）')),
                ('danger_threshold', models.PositiveIntegerField(default=6, verbose_name='危険上限（赤）')),
            ],
            options={
                'verbose_name': 'シフト設定',
                'verbose_name_plural': 'シフト設定',
            },
        ),
    ]
