# Generated by Django 5.1.1 on 2026-02-18 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_shiftsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='line_user_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='LINE User ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='通知先メール'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_via_email',
            field=models.BooleanField(default=True, verbose_name='メール通知'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_via_line',
            field=models.BooleanField(default=False, verbose_name='LINE通知'),
        ),
        migrations.AlterField(
            model_name='availabilityday',
            name='absence_category',
            field=models.CharField(blank=True, choices=[('PERSONAL', '私用休み'), ('SICK', '特例休み'), ('SUBSTITUTE', '代理休み'), ('OTHER', '冠婚葬祭・療養入院')], default='', max_length=10, verbose_name='休みカテゴリ'),
        ),
        migrations.CreateModel(
            name='ShiftNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('OPEN', '募集開始'), ('REMINDER', '締切リマインド'), ('MANUAL', '手動通知')], max_length=20, verbose_name='通知種別')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('sent_line_count', models.IntegerField(default=0, verbose_name='LINE送信数')),
                ('sent_email_count', models.IntegerField(default=0, verbose_name='メール送信数')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shifts.scheduleperiod', verbose_name='期間')),
            ],
            options={
                'verbose_name': 'シフト通知',
                'verbose_name_plural': 'シフト通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
