# Generated by Django 5.1.1 on 2026-02-22 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0058_init_user_menu_permission'),
        ('shifts', '0005_notification_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='sales.saleslocation', verbose_name='デフォルト売り場'),
        ),
        migrations.AlterField(
            model_name='availabilityday',
            name='absence_category',
            field=models.CharField(blank=True, choices=[('PERSONAL', '私用休み'), ('SICK', '収入調整'), ('SUBSTITUTE', '代理休み'), ('OTHER', '冠婚葬祭・療養入院')], default='', max_length=10, verbose_name='休みカテゴリ'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL, verbose_name='担当者'),
        ),
        migrations.CreateModel(
            name='ExternalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('can_drive', models.BooleanField(default=False, verbose_name='運転可能')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('default_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_external_staff', to='sales.saleslocation', verbose_name='デフォルト売り場')),
            ],
            options={
                'verbose_name': '外部スタッフ',
                'verbose_name_plural': '外部スタッフ',
            },
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='external_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='shifts.externalstaff', verbose_name='外部スタッフ'),
        ),
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_staff__isnull', True), ('user__isnull', False)), models.Q(('external_staff__isnull', False), ('user__isnull', True)), _connector='OR'), name='assignment_user_or_external_staff'),
        ),
    ]
