# Generated by Django 5.1.1 on 2026-02-22 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_userprofile_default_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAvailabilityDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('is_available', models.BooleanField(default=True, verbose_name='出勤可能')),
                ('external_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_days', to='shifts.externalstaff', verbose_name='外部スタッフ')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_availability_days', to='shifts.scheduleperiod', verbose_name='期間')),
            ],
            options={
                'verbose_name': '外部スタッフ出勤可能日',
                'verbose_name_plural': '外部スタッフ出勤可能日',
                'ordering': ['date'],
                'unique_together': {('external_staff', 'period', 'date')},
            },
        ),
    ]
