# Generated by Django 5.1.1 on 2026-02-23 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0058_init_user_menu_permission'),
        ('shifts', '0007_externalavailabilityday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shiftassignment',
            name='assignment_user_or_external_staff',
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='special_type',
            field=models.CharField(blank=True, choices=[('REST', '休み'), ('CANCEL', '中止')], default='', max_length=10, verbose_name='特殊種別'),
        ),
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_staff__isnull', True), ('special_type', ''), ('user__isnull', False)), models.Q(('external_staff__isnull', False), ('special_type', ''), ('user__isnull', True)), models.Q(('external_staff__isnull', True), ('special_type__in', ['REST', 'CANCEL']), ('user__isnull', True)), _connector='OR'), name='assignment_user_or_external_staff'),
        ),
    ]
