# Generated by Django 5.1.1 on 2026-02-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_scheduleperiod_shared_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('OPEN', 'シフト募集開始'), ('REMINDER', '締切リマインド（自動）'), ('MANUAL', '締切リマインド（手動）'), ('PUBLISHED', 'シフト公開'), ('ASSIGNMENT_CHANGED', 'シフト変更通知')], max_length=30, unique=True, verbose_name='通知種別')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='有効')),
                ('title_template', models.CharField(max_length=200, verbose_name='タイトルテンプレート')),
                ('body_template', models.TextField(verbose_name='本文テンプレート')),
            ],
            options={
                'verbose_name': '通知テンプレート',
                'verbose_name_plural': '通知テンプレート',
            },
        ),
        migrations.AlterField(
            model_name='shiftnotification',
            name='notification_type',
            field=models.CharField(choices=[('OPEN', '募集開始'), ('REMINDER', '締切リマインド'), ('MANUAL', '手動通知'), ('PUBLISHED', 'シフト公開'), ('ASSIGNMENT_CHANGED', 'シフト変更通知')], max_length=20, verbose_name='通知種別'),
        ),
    ]
