# Generated by Django 5.1.1 on 2026-06-09 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0071_qr_override_fields'),
        ('shifts', '0012_add_recruiting_special_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineLinkAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_uid', models.CharField(max_length=64, unique=True, verbose_name='LINE User ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='試行回数')),
                ('window_start', models.DateTimeField(verbose_name='計測開始')),
            ],
            options={
                'verbose_name': 'LINE連携試行',
                'verbose_name_plural': 'LINE連携試行',
            },
        ),
        migrations.CreateModel(
            name='LineLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, verbose_name='連携コード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='発行日時')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用日時')),
            ],
            options={
                'verbose_name': 'LINE連携コード',
                'verbose_name_plural': 'LINE連携コード',
            },
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('line_user_id', ''), _negated=True), fields=('line_user_id',), name='uniq_line_user_id_nonblank'),
        ),
        migrations.AddField(
            model_name='linelinkcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_link_codes', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddIndex(
            model_name='linelinkcode',
            index=models.Index(fields=['code', 'used_at'], name='shifts_line_code_deb3f6_idx'),
        ),
    ]
