# Generated by Django 5.1.1 on 2026-06-17 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0072_reservation_fields'),
        ('shifts', '0013_linelinkattempt_linelinkcode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedShiftSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('special_type', models.CharField(blank=True, choices=[('REST', '休み'), ('CANCEL', '中止'), ('RECRUITING', '募集中')], default='', max_length=10, verbose_name='特殊種別')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('external_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_snapshots', to='shifts.externalstaff', verbose_name='外部スタッフ')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_snapshots', to='shifts.scheduleperiod', verbose_name='期間')),
                ('sales_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_snapshots', to='sales.saleslocation', verbose_name='売り場')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
            ],
            options={
                'verbose_name': '公開シフトスナップショット',
                'verbose_name_plural': '公開シフトスナップショット',
                'ordering': ['date', 'sales_location'],
                'unique_together': {('period', 'date', 'sales_location')},
            },
        ),
    ]
