# Generated by Django 5.1.1 on 2026-06-17 09:23

from django.db import migrations


def backfill(apps, schema_editor):
    """既存の公開済み期間について、現在の割当を公開ベースラインとして取り込む。
    これが無いと、移行直後にスタッフ画面（スナップショット参照）が空になる。"""
    SchedulePeriod = apps.get_model('shifts', 'SchedulePeriod')
    ShiftAssignment = apps.get_model('shifts', 'ShiftAssignment')
    PublishedShiftSnapshot = apps.get_model('shifts', 'PublishedShiftSnapshot')

    for period in SchedulePeriod.objects.filter(status='PUBLISHED'):
        # 既存スナップショットがあれば作り直し
        PublishedShiftSnapshot.objects.filter(period=period).delete()
        assignments = ShiftAssignment.objects.filter(
            date__gte=period.start_date, date__lte=period.end_date,
        )
        objs = [
            PublishedShiftSnapshot(
                period=period,
                date=a.date,
                sales_location_id=a.sales_location_id,
                user_id=a.user_id,
                external_staff_id=a.external_staff_id,
                special_type=a.special_type,
            )
            for a in assignments
        ]
        PublishedShiftSnapshot.objects.bulk_create(objs)


def reverse(apps, schema_editor):
    PublishedShiftSnapshot = apps.get_model('shifts', 'PublishedShiftSnapshot')
    PublishedShiftSnapshot.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0014_publishedshiftsnapshot'),
    ]

    operations = [
        migrations.RunPython(backfill, reverse),
    ]
