# Generated by Django 5.1.1 on 2026-09-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0015_backfill_published_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assignment_priority',
            field=models.PositiveIntegerField(default=100, help_text='数字が小さいほど優先。同じ売り場を複数人が希望したとき、小さい人が優先的に配置される。', verbose_name='割当優先度'),
        ),
    ]
