# Generated by Django 5.1.1 on 2026-04-07 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('streak', '連続達成'), ('cumulative', '累計達成'), ('special', '特別')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('threshold', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '実績バッジ',
                'verbose_name_plural': '実績バッジ',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MissionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_type', models.CharField(choices=[('sales_count', '販売数達成'), ('zero_waste', '廃棄ゼロ'), ('sold_out', '完売達成'), ('sold_out_time', '早期完売'), ('revenue', '売上金額達成')], max_length=30, unique=True)),
                ('name_template', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_xp', models.PositiveIntegerField(default=10)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ミッションテンプレート',
                'verbose_name_plural': 'ミッションテンプレート',
            },
        ),
        migrations.CreateModel(
            name='QuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(default='見習い戦士', max_length=50)),
                ('character_image', models.CharField(default='quest/img/characters/lv01_apprentice.svg', max_length=100)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_mission_date', models.DateField(blank=True, null=True)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quest_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'クエストプロフィール',
                'verbose_name_plural': 'クエストプロフィール',
            },
        ),
        migrations.CreateModel(
            name='DailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('pending', '進行中'), ('completed', '達成'), ('failed', '未達成')], default='pending', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_missions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.missiontemplate')),
            ],
            options={
                'verbose_name': 'デイリーミッション',
                'verbose_name_plural': 'デイリーミッション',
                'ordering': ['-date', 'template'],
                'unique_together': {('user', 'date', 'template')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザー実績',
                'verbose_name_plural': 'ユーザー実績',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
