# Generated by Django 5.1.1 on 2026-04-07 12:53

from django.db import migrations


def seed_data(apps, schema_editor):
    MissionTemplate = apps.get_model('quest', 'MissionTemplate')
    Achievement = apps.get_model('quest', 'Achievement')

    # ミッションテンプレート
    templates = [
        {
            'mission_type': 'sales_count',
            'name_template': '{count}食以上を販売せよ！',
            'description': '目標数以上の弁当を販売しよう',
            'base_xp': 15,
            'icon': 'sword',
            'is_active': True,
        },
        {
            'mission_type': 'zero_waste',
            'name_template': '廃棄ゼロを達成せよ！',
            'description': '残数ゼロで一日を終えよう',
            'base_xp': 25,
            'icon': 'shield',
            'is_active': True,
        },
        {
            'mission_type': 'sold_out',
            'name_template': '完売を達成せよ！',
            'description': 'いずれかの商品を完売させよう',
            'base_xp': 20,
            'icon': 'star',
            'is_active': True,
        },
        {
            'mission_type': 'sold_out_time',
            'name_template': '12:30までに完売せよ！',
            'description': '早期完売で最高の効率を目指そう',
            'base_xp': 30,
            'icon': 'clock',
            'is_active': True,
        },
        {
            'mission_type': 'revenue',
            'name_template': '売上{amount}円以上を達成せよ！',
            'description': '目標売上金額を達成しよう',
            'base_xp': 20,
            'icon': 'coin',
            'is_active': True,
        },
    ]
    for t in templates:
        MissionTemplate.objects.get_or_create(
            mission_type=t['mission_type'],
            defaults=t,
        )

    # 実績バッジ
    achievements = [
        {
            'code': 'streak_3',
            'name': '3日連続達成',
            'description': '3日連続でミッションを達成した',
            'category': 'streak',
            'icon': 'quest/img/badges/streak_3.svg',
            'xp_reward': 30,
            'threshold': 3,
            'sort_order': 1,
        },
        {
            'code': 'streak_7',
            'name': '一週間の勇者',
            'description': '7日連続でミッションを達成した',
            'category': 'streak',
            'icon': 'quest/img/badges/streak_7.svg',
            'xp_reward': 100,
            'threshold': 7,
            'sort_order': 2,
        },
        {
            'code': 'streak_14',
            'name': '鉄人',
            'description': '14日連続でミッションを達成した',
            'category': 'streak',
            'icon': 'quest/img/badges/streak_14.svg',
            'xp_reward': 200,
            'threshold': 14,
            'sort_order': 3,
        },
        {
            'code': 'streak_30',
            'name': '伝説の記録',
            'description': '30日連続でミッションを達成した',
            'category': 'streak',
            'icon': 'quest/img/badges/streak_30.svg',
            'xp_reward': 500,
            'threshold': 30,
            'sort_order': 4,
        },
        {
            'code': 'total_missions_10',
            'name': '10ミッション達成',
            'description': '累計10のミッションを達成した',
            'category': 'cumulative',
            'icon': 'quest/img/badges/missions_10.svg',
            'xp_reward': 50,
            'threshold': 10,
            'sort_order': 10,
        },
        {
            'code': 'total_missions_50',
            'name': '50ミッション達成',
            'description': '累計50のミッションを達成した',
            'category': 'cumulative',
            'icon': 'quest/img/badges/missions_50.svg',
            'xp_reward': 150,
            'threshold': 50,
            'sort_order': 11,
        },
        {
            'code': 'total_missions_100',
            'name': '100ミッション達成',
            'description': '累計100のミッションを達成した',
            'category': 'cumulative',
            'icon': 'quest/img/badges/missions_100.svg',
            'xp_reward': 300,
            'threshold': 100,
            'sort_order': 12,
        },
        {
            'code': 'first_sold_out',
            'name': 'はじめての完売',
            'description': '初めて完売ミッションを達成した',
            'category': 'special',
            'icon': 'quest/img/badges/first_sold_out.svg',
            'xp_reward': 50,
            'threshold': 0,
            'sort_order': 20,
        },
        {
            'code': 'first_zero_waste',
            'name': 'はじめての廃棄ゼロ',
            'description': '初めて廃棄ゼロミッションを達成した',
            'category': 'special',
            'icon': 'quest/img/badges/first_zero_waste.svg',
            'xp_reward': 50,
            'threshold': 0,
            'sort_order': 21,
        },
        {
            'code': 'perfect_day',
            'name': 'パーフェクトデイ',
            'description': '1日の全ミッションを達成した',
            'category': 'special',
            'icon': 'quest/img/badges/perfect_day.svg',
            'xp_reward': 100,
            'threshold': 0,
            'sort_order': 22,
        },
    ]
    for a in achievements:
        Achievement.objects.get_or_create(
            code=a['code'],
            defaults=a,
        )


def reverse_seed(apps, schema_editor):
    MissionTemplate = apps.get_model('quest', 'MissionTemplate')
    Achievement = apps.get_model('quest', 'Achievement')
    MissionTemplate.objects.all().delete()
    Achievement.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed),
    ]
