# Generated by Django 5.1.1 on 2026-04-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='questprofile',
            name='is_participating',
            field=models.BooleanField(default=False, verbose_name='参加中'),
        ),
    ]
