# Generated by Django 5.1.1 on 2026-04-12 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_add_is_participating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='questprofile',
            name='character_image',
            field=models.CharField(default='quest/img/titles/lv001_minarai.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='questprofile',
            name='title',
            field=models.CharField(default='見習い販売員', max_length=50),
        ),
        migrations.CreateModel(
            name='CelebrationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_level', models.PositiveIntegerField(default=1)),
                ('new_level', models.PositiveIntegerField(default=1)),
                ('leveled_up', models.BooleanField(default=False)),
                ('prev_title', models.CharField(blank=True, max_length=50)),
                ('new_title', models.CharField(blank=True, max_length=50)),
                ('title_changed', models.BooleanField(default=False)),
                ('new_character_image', models.CharField(blank=True, max_length=100)),
                ('xp_gained', models.PositiveIntegerField(default=0)),
                ('completed_missions_json', models.JSONField(default=list)),
                ('new_achievements_json', models.JSONField(default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebration_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '演出キュー',
                'verbose_name_plural': '演出キュー',
                'ordering': ['-created_at'],
            },
        ),
    ]
