# Generated by Django 5.1.1 on 2026-03-22 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0063_usermenupermission_can_view_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('B2B', '法人'), ('INDIVIDUAL', '個人')], default='B2B', max_length=10, verbose_name='顧客種別')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='会社名')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='担当者名')),
                ('name', models.CharField(max_length=100, verbose_name='顧客名')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵便番号')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='FAX番号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('price_type', models.CharField(choices=[('A', '価格A'), ('B', '価格B'), ('C', '価格C')], default='A', max_length=1, verbose_name='価格タイプ')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
                'ordering': ['company_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='受注番号')),
                ('order_date', models.DateField(verbose_name='受注日')),
                ('delivery_date', models.DateField(db_index=True, verbose_name='納品日')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.customer', verbose_name='顧客')),
            ],
            options={
                'verbose_name': '受注',
                'verbose_name_plural': '受注',
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='商品名')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='単価')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='小計')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='受注')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '受注明細',
                'verbose_name_plural': '受注明細',
            },
        ),
    ]
