# Generated by Django 5.1.1 on 2026-03-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity_large',
            field=models.PositiveIntegerField(default=0, verbose_name='大盛り数'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_regular',
            field=models.PositiveIntegerField(default=0, verbose_name='普通盛り数'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_small',
            field=models.PositiveIntegerField(default=0, verbose_name='小盛り数'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='数量（合計）'),
        ),
    ]
