# Generated by Django 5.1.1 on 2026-03-22 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_quantity_large_orderitem_quantity_regular_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_regular',
            field=models.BooleanField(default=False, verbose_name='定期注文'),
        ),
        migrations.AddField(
            model_name='order',
            name='pdf_printed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PDF出力日時'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('customer', 'delivery_date'), name='unique_customer_delivery_date'),
        ),
    ]
