# Generated by Django 5.1.1 on 2026-03-23 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customer_is_regular_order_pdf_printed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='支払い方法名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '支払い方法',
                'verbose_name_plural': '支払い方法',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.paymentmethod', verbose_name='支払い方法'),
        ),
    ]
