# Generated by Django 5.1.1 on 2026-03-23 12:50

from django.db import migrations


def seed_payment_methods(apps, schema_editor):
    PaymentMethod = apps.get_model('orders', 'PaymentMethod')
    methods = [
        {'name': '現金払い', 'sort_order': 1},
        {'name': '月末請求書払い', 'sort_order': 2},
        {'name': 'PayPay', 'sort_order': 3},
    ]
    for m in methods:
        PaymentMethod.objects.get_or_create(name=m['name'], defaults={'sort_order': m['sort_order']})


def reverse_seed(apps, schema_editor):
    PaymentMethod = apps.get_model('orders', 'PaymentMethod')
    PaymentMethod.objects.filter(name__in=['現金払い', '月末請求書払い', 'PayPay']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_paymentmethod_customer_payment_method'),
    ]

    operations = [
        migrations.RunPython(seed_payment_methods, reverse_seed),
    ]
