# Generated by Django 5.1.1 on 2026-03-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_seed_payment_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=8, max_digits=5, verbose_name='消費税率（%）')),
                ('company_name', models.CharField(default='有限会社ランチサービスネットワーク', max_length=200, verbose_name='会社名')),
                ('postal_code', models.CharField(default='〒224-0021', max_length=10, verbose_name='郵便番号')),
                ('address', models.CharField(default='横浜市都筑区北山田1-1-18', max_length=300, verbose_name='住所')),
                ('tel', models.CharField(default='045-593-6656', max_length=20, verbose_name='電話番号')),
                ('fax', models.CharField(default='045-592-8424', max_length=20, verbose_name='FAX番号')),
            ],
            options={
                'verbose_name': '受注設定',
                'verbose_name_plural': '受注設定',
            },
        ),
    ]
