# Generated by Django 5.1.1 on 2026-03-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_ordersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersettings',
            name='invoice_number',
            field=models.CharField(default='T4020002059715', max_length=20, verbose_name='登録番号'),
        ),
    ]
