# Generated by Django 5.1.1 on 2026-03-25 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordersettings_invoice_number'),
        ('sales', '0063_usermenupermission_can_view_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bento_type',
            field=models.CharField(choices=[('REGULAR', '通常弁当'), ('CATERING', '仕出し弁当')], default='REGULAR', max_length=10, verbose_name='弁当種別'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.product', verbose_name='商品'),
        ),
    ]
