# Generated by Django 5.1.1 on 2026-03-25 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_customer_bento_type_orderitem_product_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='単価')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '追加商品',
                'verbose_name_plural': '追加商品',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='単価')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='小計')),
                ('extra_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.extraproduct', verbose_name='追加商品マスタ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_items', to='orders.order', verbose_name='受注')),
            ],
            options={
                'verbose_name': '追加商品明細',
                'verbose_name_plural': '追加商品明細',
            },
        ),
    ]
