# Generated by Django 5.1.1 on 2026-03-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_extraproduct_orderextraitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customer_type', 'company_name', 'department', 'name'], 'verbose_name': '顧客', 'verbose_name_plural': '顧客'},
        ),
        migrations.AddField(
            model_name='customer',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='部署名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='顧客名'),
        ),
    ]
