# Generated by Django 5.1.1 on 2026-03-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_customer_options_customer_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='regular_type',
            field=models.CharField(blank=True, choices=[('WEEKDAY', '平日毎日（月〜金）'), ('CUSTOM', '曜日指定')], default='WEEKDAY', max_length=10, verbose_name='定期スケジュール'),
        ),
        migrations.AddField(
            model_name='customer',
            name='schedule_fri',
            field=models.BooleanField(default=False, verbose_name='金'),
        ),
        migrations.AddField(
            model_name='customer',
            name='schedule_mon',
            field=models.BooleanField(default=False, verbose_name='月'),
        ),
        migrations.AddField(
            model_name='customer',
            name='schedule_sat',
            field=models.BooleanField(default=False, verbose_name='土'),
        ),
        migrations.AddField(
            model_name='customer',
            name='schedule_sun',
            field=models.BooleanField(default=False, verbose_name='日'),
        ),
        migrations.AddField(
            model_name='customer',
            name='schedule_thu',
            field=models.BooleanField(default=False, verbose_name='木'),
        ),
        migrations.AddField(
            model_name='customer',
            name='schedule_tue',
            field=models.BooleanField(default=False, verbose_name='火'),
        ),
        migrations.AddField(
            model_name='customer',
            name='schedule_wed',
            field=models.BooleanField(default=False, verbose_name='水'),
        ),
    ]
