# Generated by Django 5.1.1 on 2026-03-29 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_deliverybin_customer_delivery_bin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUserMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_dashboard', models.BooleanField(default=True, verbose_name='受注ダッシュボード')),
                ('can_view_delivery_list', models.BooleanField(default=True, verbose_name='配達リスト')),
                ('can_view_new_order', models.BooleanField(default=True, verbose_name='新規受注')),
                ('can_view_customers', models.BooleanField(default=True, verbose_name='顧客一覧')),
                ('can_view_settings', models.BooleanField(default=True, verbose_name='設定')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_menu_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '受注メニュー表示設定',
                'verbose_name_plural': '受注メニュー表示設定',
            },
        ),
    ]
