# Generated by Django 5.1.1 on 2026-03-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderusermenupermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_price_large',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='独自大盛り割増'),
        ),
        migrations.AddField(
            model_name='customer',
            name='custom_price_normal',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='独自価格（★なし）'),
        ),
        migrations.AddField(
            model_name='customer',
            name='custom_price_star',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='独自価格（★あり）'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='price_type',
            field=models.CharField(choices=[('A', '価格A'), ('B', '価格B'), ('C', '価格C'), ('CUSTOM', '独自価格')], default='A', max_length=6, verbose_name='価格タイプ'),
        ),
    ]
