# Generated by Django 5.1.1 on 2026-03-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_customer_custom_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderusermenupermission',
            name='can_view_csv_export',
            field=models.BooleanField(default=True, verbose_name='CSVエクスポート'),
        ),
    ]
