# Generated by Django 5.1.1 on 2026-04-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_add_can_view_csv_export_to_orderusermenupermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_memo',
            field=models.CharField(default='お弁当代', max_length=100, verbose_name='但し書き'),
        ),
    ]
