# Generated by Django 5.1.1 on 2026-04-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_receipt_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(db_index=True, verbose_name='配達日')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='完了日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer', verbose_name='顧客')),
                ('delivery_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.deliverybin', verbose_name='配達便')),
            ],
            options={
                'verbose_name': '配達完了',
                'verbose_name_plural': '配達完了',
                'unique_together': {('customer', 'delivery_date')},
            },
        ),
    ]
