# Generated by Django 5.1.1 on 2026-04-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_deliverycompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='include_in_total',
            field=models.BooleanField(default=True, verbose_name='全体注文数に含める'),
        ),
    ]
