# Generated by Django 5.1.1 on 2026-07-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_customer_include_in_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invoice_timing',
            field=models.CharField(blank=True, choices=[('IMMEDIATE', '即時発行'), ('MONTH_END', '月末締め発行')], default='', max_length=10, verbose_name='請求書発行タイミング'),
        ),
    ]
