# Generated by Django 5.1.1 on 2026-07-28 03:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_customer_invoice_timing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_pattern',
            field=models.CharField(choices=[('MONTH_END', '月末締め'), ('IMMEDIATE', '即時発行'), ('SPOT', 'スポットまとめ')], default='MONTH_END', max_length=10, verbose_name='請求パターン'),
        ),
        migrations.AddField(
            model_name='orderusermenupermission',
            name='can_view_adjustments',
            field=models.BooleanField(default=True, verbose_name='受注調整'),
        ),
        migrations.CreateModel(
            name='OrderAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RETURN', '返品'), ('CANCEL', '取消'), ('DISCOUNT', '値引き'), ('OTHER', 'その他')], max_length=10, verbose_name='種別')),
                ('settlement', models.CharField(choices=[('CREDIT', '請求相殺'), ('CASH', '現金・振込返金')], max_length=10, verbose_name='返金方法')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='調整額（税込）')),
                ('reason', models.TextField(verbose_name='理由')),
                ('occurred_on', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='発生日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='orders.order', verbose_name='受注')),
            ],
            options={
                'verbose_name': '受注調整',
                'verbose_name_plural': '受注調整',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='商品名')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='単価（税込）')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='小計')),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.orderadjustment', verbose_name='受注調整')),
                ('order_extra_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderextraitem', verbose_name='対象追加明細')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderitem', verbose_name='対象明細')),
            ],
            options={
                'verbose_name': '受注調整明細',
                'verbose_name_plural': '受注調整明細',
            },
        ),
    ]
