# Generated by Django 5.1.1 on 2026-07-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_billing_pattern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_pattern',
            field=models.CharField(choices=[('MONTH_END', '月末締め'), ('IMMEDIATE', '即時発行')], default='MONTH_END', max_length=10, verbose_name='請求パターン'),
        ),
    ]
