# Generated by Django 5.1.1 on 2026-07-28 07:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_order_billing_pattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderusermenupermission',
            name='can_view_invoices',
            field=models.BooleanField(default=True, verbose_name='請求書'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30, unique=True, verbose_name='請求書番号')),
                ('pattern', models.CharField(choices=[('MONTH_END', '月末締め'), ('IMMEDIATE', '即時/スポット')], default='MONTH_END', max_length=10, verbose_name='発行パターン')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='対象期間（開始）')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='対象期間（終了）')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='発行日')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='支払期日')),
                ('status', models.CharField(choices=[('DRAFT', '下書き'), ('ISSUED', '発行済み'), ('PAID', '入金済み'), ('VOID', '取消')], db_index=True, default='ISSUED', max_length=10, verbose_name='状態')),
                ('registration_number', models.CharField(blank=True, max_length=20, verbose_name='登録番号（T番号）')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=8, max_digits=5, verbose_name='税率（%）')),
                ('charge_total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='受注合計（税込）')),
                ('credit_total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='控除合計（税込）')),
                ('net_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='請求金額（税込）')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='消費税額')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('void_reason', models.TextField(blank=True, verbose_name='取消理由')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orders.customer', verbose_name='顧客')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_invoices', to=settings.AUTH_USER_MODEL, verbose_name='発行者')),
            ],
            options={
                'verbose_name': '請求書',
                'verbose_name_plural': '請求書',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.invoice', verbose_name='請求書'),
        ),
        migrations.AddField(
            model_name='orderadjustment',
            name='billed_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='orders.invoice', verbose_name='取込請求書'),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('ORDER', '受注'), ('ADJUSTMENT', '調整（控除）')], max_length=12, verbose_name='種別')),
                ('line_date', models.DateField(verbose_name='日付')),
                ('label', models.CharField(max_length=255, verbose_name='内容')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='数量')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='単価（税込）')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='金額（税込）')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='orders.orderadjustment', verbose_name='元調整')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.invoice', verbose_name='請求書')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='orders.order', verbose_name='元受注')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderitem', verbose_name='元受注明細')),
            ],
            options={
                'verbose_name': '請求明細',
                'verbose_name_plural': '請求明細',
                'ordering': ['sort_order', 'line_date', 'id'],
            },
        ),
    ]
