# Generated by Django 5.1.1 on 2026-07-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_orderusermenupermission_can_view_invoices_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='quantity_large',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='うち大盛り数'),
        ),
    ]
