# Generated by Django 5.1.1 on 2026-07-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_invoiceline_quantity_large'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_info',
            field=models.TextField(blank=True, default='', verbose_name='振込先'),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='bank_info',
            field=models.TextField(blank=True, default='', verbose_name='振込先'),
        ),
    ]
