# Generated by Django 5.1.1 on 2026-07-30 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_invoice_bank_info_ordersettings_bank_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='口座の識別名')),
                ('info', models.TextField(verbose_name='振込先（請求書印字用）')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '振込先口座',
                'verbose_name_plural': '振込先口座',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='bank_info',
            field=models.TextField(blank=True, default='', verbose_name='デフォルト振込先'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.bankaccount', verbose_name='振込先口座'),
        ),
    ]
