# Generated by Django 5.1.1 on 2026-07-30 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_bankaccount_alter_ordersettings_bank_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='orders.orderadjustment', verbose_name='元調整'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='orders.order', verbose_name='元受注'),
        ),
    ]
