# Generated by Django 5.1.1 on 2026-07-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_invoiceline_adjustment_alter_invoiceline_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invoice_delivery',
            field=models.CharField(choices=[('MAIL', '郵送（原本）'), ('EMAIL', 'メール配信')], default='MAIL', max_length=10, verbose_name='請求書の配信方法'),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='seal_image_data',
            field=models.TextField(blank=True, default='', verbose_name='社印画像'),
        ),
    ]
