# Generated by Django 5.1.1 on 2026-09-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_customer_invoice_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuWeekAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True, verbose_name='適用開始（納品日）')),
                ('end_date', models.DateField(verbose_name='適用終了（納品日・含む）')),
                ('week', models.CharField(max_length=10, verbose_name='適用するメニュー週')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='メモ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'メニュー週の割当',
                'verbose_name_plural': 'メニュー週の割当',
                'ordering': ['-start_date'],
            },
        ),
    ]
