# Generated by Django 5.1.1 on 2026-05-20 12:13

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('closing_day', models.PositiveSmallIntegerField(default=15, verbose_name='締め日')),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=Decimal('0.25'), max_digits=4, verbose_name='時間外割増率')),
                ('over60h_rate', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4, verbose_name='月60時間超の時間外割増率')),
                ('night_rate', models.DecimalField(decimal_places=2, default=Decimal('0.25'), max_digits=4, verbose_name='深夜割増率')),
                ('holiday_rate', models.DecimalField(decimal_places=2, default=Decimal('0.35'), max_digits=4, verbose_name='休日割増率')),
                ('night_start', models.TimeField(default=datetime.time(22, 0), verbose_name='深夜帯 開始')),
                ('night_end', models.TimeField(default=datetime.time(5, 0), verbose_name='深夜帯 終了')),
                ('break_rule', models.TextField(blank=True, default='労働6時間超で45分／8時間超で60分を自動控除（要・社労士確認）', verbose_name='休憩控除ルール')),
                ('rounding_rule', models.CharField(default='1分単位（丸めなし）', max_length=64, verbose_name='端数処理')),
            ],
            options={
                'verbose_name': '給与設定',
                'verbose_name_plural': '給与設定',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('business_unit', models.CharField(choices=[('cafeteria', '食堂事業'), ('sales', '販売事業')], max_length=16, verbose_name='事業区分')),
                ('name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='所在地')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
                'ordering': ['business_unit', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('display_name', models.CharField(max_length=100, verbose_name='氏名')),
                ('business_unit', models.CharField(choices=[('cafeteria', '食堂事業'), ('sales', '販売事業')], max_length=16, verbose_name='事業区分')),
                ('employment_type', models.CharField(choices=[('hourly', '時給')], default='hourly', max_length=16, verbose_name='雇用形態')),
                ('hired_on', models.DateField(blank=True, null=True, verbose_name='入社日')),
                ('is_active', models.BooleanField(default=True, verbose_name='在籍')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_staff', to=settings.AUTH_USER_MODEL, verbose_name='ログインユーザー')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='attendance.store', verbose_name='所属店舗')),
            ],
            options={
                'verbose_name': 'スタッフ',
                'verbose_name_plural': 'スタッフ',
                'ordering': ['business_unit', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='HourlyWage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('amount', models.PositiveIntegerField(verbose_name='時給（円）')),
                ('effective_from', models.DateField(verbose_name='適用開始日')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_wages', to='attendance.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '時給',
                'verbose_name_plural': '時給',
                'ordering': ['staff', '-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('staff', 'effective_from'), name='uniq_staff_wage_effective_from')],
            },
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('kind', models.CharField(choices=[('clock_in', '出勤'), ('clock_out', '退勤')], max_length=16, verbose_name='種別')),
                ('recorded_at', models.DateTimeField(verbose_name='打刻日時')),
                ('work_date', models.DateField(verbose_name='勤務日')),
                ('source', models.CharField(choices=[('app', 'スマホ打刻'), ('manual', '管理者まとめ入力')], default='app', max_length=16, verbose_name='入力経路')),
                ('is_corrected', models.BooleanField(default=False, verbose_name='修正済み')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='取り消し済み')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='備考')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to='attendance.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '打刻',
                'verbose_name_plural': '打刻',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['staff', 'work_date'], name='attendance__staff_i_9aaef1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('staff', 'work_date', 'kind'), name='uniq_active_punch_per_day_kind')],
            },
        ),
    ]
