# Generated by Django 5.1.1 on 2026-05-21 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollsetting',
            name='break_rule',
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='break1_deduct_minutes',
            field=models.PositiveSmallIntegerField(default=45, verbose_name='休憩控除 控除分数1（分）'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='break1_threshold_minutes',
            field=models.PositiveSmallIntegerField(default=360, verbose_name='休憩控除 しきい値1（拘束・分超）'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='break2_deduct_minutes',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='休憩控除 控除分数2（分）'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='break2_threshold_minutes',
            field=models.PositiveSmallIntegerField(default=480, verbose_name='休憩控除 しきい値2（拘束・分超）'),
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('period_start', models.DateField(verbose_name='期間開始日')),
                ('period_end', models.DateField(unique=True, verbose_name='期間終了日（締め日）')),
                ('closing_day', models.PositiveSmallIntegerField(verbose_name='締め日（スナップショット）')),
                ('is_closed', models.BooleanField(default=False, verbose_name='締め済み')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='締め日時')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_payroll_periods', to=settings.AUTH_USER_MODEL, verbose_name='締め実行者')),
            ],
            options={
                'verbose_name': '締め期間',
                'verbose_name_plural': '締め期間',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='TimeRecordEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('action', models.CharField(choices=[('created', '新規入力'), ('updated', '時刻修正'), ('deleted', '取り消し')], max_length=16, verbose_name='操作')),
                ('before_value', models.CharField(blank=True, default='—', max_length=32, verbose_name='修正前')),
                ('after_value', models.CharField(blank=True, default='—', max_length=32, verbose_name='修正後')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='理由')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_record_edits', to=settings.AUTH_USER_MODEL, verbose_name='修正者')),
                ('time_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='attendance.timerecord', verbose_name='対象の打刻')),
            ],
            options={
                'verbose_name': '打刻の修正履歴',
                'verbose_name_plural': '打刻の修正履歴',
                'ordering': ['-created_at'],
            },
        ),
    ]
