# Generated by Django 5.1.1 on 2026-05-21 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_payrollsetting_break_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsetting',
            name='min_wage',
            field=models.PositiveIntegerField(default=1226, verbose_name='最低賃金（円）'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='wage_rounding_unit',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='賃金の丸め単位（円）'),
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('work_days', models.PositiveSmallIntegerField(default=0, verbose_name='勤務日数')),
                ('work_minutes', models.PositiveIntegerField(default=0, verbose_name='実働（分）')),
                ('overtime_minutes', models.PositiveIntegerField(default=0, verbose_name='時間外（分）')),
                ('over60h_minutes', models.PositiveIntegerField(default=0, verbose_name='うち月60時間超（分）')),
                ('night_minutes', models.PositiveIntegerField(default=0, verbose_name='深夜（分）')),
                ('holiday_minutes', models.PositiveIntegerField(default=0, verbose_name='休日（分）')),
                ('hourly_wage', models.PositiveIntegerField(default=0, verbose_name='時給（円）')),
                ('base_wage_yen', models.PositiveIntegerField(default=0, verbose_name='基本賃金（円）')),
                ('overtime_premium_yen', models.PositiveIntegerField(default=0, verbose_name='時間外割増（円）')),
                ('night_premium_yen', models.PositiveIntegerField(default=0, verbose_name='深夜割増（円）')),
                ('holiday_premium_yen', models.PositiveIntegerField(default=0, verbose_name='休日割増（円）')),
                ('total_yen', models.PositiveIntegerField(default=0, verbose_name='支給額（円）')),
                ('confirmed_at', models.DateTimeField(verbose_name='確定日時')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_payslips', to=settings.AUTH_USER_MODEL, verbose_name='確定者')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='attendance.payrollperiod', verbose_name='締め期間')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='attendance.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '給与明細',
                'verbose_name_plural': '給与明細',
                'ordering': ['-payroll_period__period_end', 'staff'],
                'constraints': [models.UniqueConstraint(fields=('payroll_period', 'staff'), name='uniq_payslip_per_period_staff')],
            },
        ),
    ]
