# Generated by Django 5.1.1 on 2026-05-22 16:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_payrollsetting_min_wage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsetting',
            name='employment_insurance_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0055'), max_digits=6, verbose_name='雇用保険料率（労働者負担）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='commute_allowance_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='通勤手当（円）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employment_insurance_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='雇用保険料（円）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='gross_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='総支給額（円）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='health_insurance_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='健康保険料（円）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='income_tax_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='所得税（円）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='net_pay_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='差引支給額（円）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='nursing_insurance_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='介護保険料（円）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='other_allowance_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='その他手当（円）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='other_deduction_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='その他控除（円）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pension_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='厚生年金保険料（円）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='resident_tax_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='住民税（円）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_deduction_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='控除合計（円）'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='total_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='賃金計（基本＋割増）（円）'),
        ),
        migrations.CreateModel(
            name='StaffPayrollProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('commute_allowance', models.PositiveIntegerField(default=0, help_text='非課税扱い（暫定）。所得税の課税対象から除く', verbose_name='通勤手当（月額・円）')),
                ('other_allowance', models.PositiveIntegerField(default=0, verbose_name='その他手当（月額・円）')),
                ('other_allowance_name', models.CharField(blank=True, default='その他手当', max_length=32, verbose_name='その他手当の名称')),
                ('health_insurance', models.PositiveIntegerField(default=0, verbose_name='健康保険料（月額・円）')),
                ('nursing_insurance', models.PositiveIntegerField(default=0, verbose_name='介護保険料（月額・円）')),
                ('pension_insurance', models.PositiveIntegerField(default=0, verbose_name='厚生年金保険料（月額・円）')),
                ('resident_tax', models.PositiveIntegerField(default=0, verbose_name='住民税（月額・円）')),
                ('other_deduction', models.PositiveIntegerField(default=0, verbose_name='その他控除（月額・円）')),
                ('other_deduction_name', models.CharField(blank=True, default='その他控除', max_length=32, verbose_name='その他控除の名称')),
                ('dependents_count', models.PositiveSmallIntegerField(default=0, help_text='所得税計算用。源泉控除対象配偶者＋源泉控除対象親族の数', verbose_name='扶養親族等の数')),
                ('employment_insurance_enrolled', models.BooleanField(default=True, verbose_name='雇用保険に加入')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_profile', to='attendance.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '給与プロフィール',
                'verbose_name_plural': '給与プロフィール',
            },
        ),
    ]
