# Generated by Django 5.1.1 on 2026-05-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_payrollsetting_employment_insurance_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='net_pay_yen',
            field=models.IntegerField(default=0, verbose_name='差引支給額（円）'),
        ),
    ]
