# Generated by Django 5.1.1 on 2026-05-23 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_payslip_net_pay_yen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualWorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('work_days', models.PositiveSmallIntegerField(default=0, verbose_name='勤務日数')),
                ('work_minutes', models.PositiveIntegerField(default=0, verbose_name='勤務時間（分）')),
                ('overtime_minutes', models.PositiveIntegerField(default=0, verbose_name='時間外時間（分）')),
                ('night_minutes', models.PositiveIntegerField(default=0, verbose_name='深夜時間（分）')),
                ('holiday_minutes', models.PositiveIntegerField(default=0, verbose_name='休日時間（分）')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='備考')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_hours', to='attendance.payrollperiod', verbose_name='締め期間')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_hours', to='attendance.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '勤務時間（手動入力）',
                'verbose_name_plural': '勤務時間（手動入力）',
                'constraints': [models.UniqueConstraint(fields=('staff', 'payroll_period'), name='uniq_manual_hours_per_staff_period')],
            },
        ),
    ]
