# Generated by Django 5.1.1 on 2026-05-23 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_manualworkhours'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=64, verbose_name='項目名')),
                ('kind', models.CharField(choices=[('payment', '支給（追加）'), ('deduction', '控除（追加）')], max_length=16, verbose_name='区分')),
                ('amount_yen', models.PositiveIntegerField(verbose_name='金額（円）')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='備考')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='attendance.payrollperiod', verbose_name='締め期間')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip_adjustments', to='attendance.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '臨時項目',
                'verbose_name_plural': '臨時項目',
                'ordering': ['staff', 'payroll_period', 'id'],
            },
        ),
    ]
