# Generated by Django 5.1.1 on 2026-05-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_staff_punch_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualworkhours',
            name='box_wash_count',
            field=models.PositiveIntegerField(default=0, verbose_name='箱洗い数（箱）'),
        ),
        migrations.AddField(
            model_name='manualworkhours',
            name='paid_leave_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='有給取得日数（日）'),
        ),
        migrations.AddField(
            model_name='manualworkhours',
            name='peddling_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='行商回数（回）'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='box_wash_allowance_yen',
            field=models.PositiveIntegerField(default=200, help_text='販売事業部の箱洗い1箱あたりの手当額', verbose_name='箱洗い手当（円/箱）'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='peddling_allowance_yen',
            field=models.PositiveIntegerField(default=1000, help_text='販売事業部の行商1回あたりの手当額', verbose_name='行商手当（円/回）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='box_wash_allowance_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='箱洗い手当（円）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='paid_leave_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='有給手当（円）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='peddling_allowance_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='行商手当（円）'),
        ),
        migrations.AddField(
            model_name='staffpayrollprofile',
            name='scheduled_minutes_per_day',
            field=models.PositiveSmallIntegerField(default=480, help_text='有給1日あたりの支払い時間として使う。例：8時間勤務なら480分', verbose_name='1日の所定労働時間（分）'),
        ),
    ]
