# Generated by Django 5.1.1 on 2026-05-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_staff_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='company',
            field=models.CharField(choices=[('LSN', '(有)ランチサービスネットワーク'), ('LN', '(合)ランチネット'), ('LF', '(合)ランチファクトリー')], default='LSN', help_text='LSN=(有)ランチサービスネットワーク（社員／食堂事業）／LN=(合)ランチネット（販売事業の販売担当）／LF=(合)ランチファクトリー（販売事業の弁当製造担当）', max_length=8, verbose_name='会社'),
        ),
    ]
