# Generated by Django 5.1.1 on 2026-05-25 14:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_staff_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualworkhours',
            name='driver_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ドライバー回数（回）'),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='gasoline_yen_per_liter',
            field=models.PositiveIntegerField(default=0, help_text='月末にスタンド価格を確認して入力。0だとガソリン代計算しない', verbose_name='今月のガソリン単価（円/L）'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='driver_allowance_yen',
            field=models.PositiveIntegerField(default=1500, help_text='配達ドライバー1回あたりの手当額。プロフィールで「ドライバー」に該当する人のみ加算される', verbose_name='ドライバー手当（円/回）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='driver_allowance_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='ドライバー手当（円）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='gasoline_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='通勤ガソリン代（円）'),
        ),
        migrations.AddField(
            model_name='staffpayrollprofile',
            name='commute_distance_km',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='ガソリン代計算に使う。自宅↔職場の片道距離', max_digits=5, verbose_name='片道通勤距離（km）'),
        ),
        migrations.AddField(
            model_name='staffpayrollprofile',
            name='commute_method',
            field=models.CharField(choices=[('transit', '公共交通機関'), ('car', '車'), ('motorcycle', 'バイク'), ('walk', '徒歩・自転車')], default='transit', max_length=16, verbose_name='通勤手段'),
        ),
        migrations.AddField(
            model_name='staffpayrollprofile',
            name='fuel_efficiency_kml',
            field=models.DecimalField(decimal_places=1, default=Decimal('15'), help_text='ガソリン代計算に使う。一般車は15km/L目安', max_digits=4, verbose_name='燃費（km/L）'),
        ),
        migrations.AddField(
            model_name='staffpayrollprofile',
            name='is_driver',
            field=models.BooleanField(default=False, help_text='チェックを付けると給与計算でドライバー手当の入力欄が出る', verbose_name='配達ドライバー'),
        ),
    ]
