# Generated by Django 5.1.1 on 2026-05-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_manualworkhours_driver_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='staff',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '未設定'), ('male', '男性'), ('female', '女性'), ('other', 'その他')], default='', max_length=8, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='staff',
            name='job_description',
            field=models.CharField(blank=True, default='', help_text='名簿に書く業務の種類。例：「お弁当製造」「ホール販売」「配達運転手」', max_length=100, verbose_name='業務の種類'),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='連絡先'),
        ),
        migrations.AddField(
            model_name='staff',
            name='retire_reason',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='退職事由'),
        ),
        migrations.AddField(
            model_name='staff',
            name='retired_on',
            field=models.DateField(blank=True, null=True, verbose_name='退職年月日'),
        ),
    ]
