# Generated by Django 5.1.1 on 2026-05-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_staff_address_staff_birthday_staff_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='paid_leave_granted_days',
            field=models.PositiveSmallIntegerField(default=10, help_text='10月〜9月の有給年度における付与日数。労基法39条の法定値を参考に設定', verbose_name='有給付与日数（今期）'),
        ),
    ]
