# Generated by Django 5.1.1 on 2026-06-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_staff_paid_leave_granted_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualworkhours',
            name='break_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='休憩時間（分・月合計）'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='break_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='休憩（分）'),
        ),
        migrations.AlterField(
            model_name='manualworkhours',
            name='work_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='勤務時間（分・拘束）'),
        ),
    ]
