# Generated by Django 5.1.1 on 2026-06-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_manualworkhours_break_minutes_payslip_break_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='break_deduction_yen',
            field=models.PositiveIntegerField(default=0, verbose_name='休憩控除（円）'),
        ),
    ]
