# Generated by Django 5.1.1 on 2026-06-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_payslip_break_deduction_yen'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='normal_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='通常時間（分）'),
        ),
    ]
