# Generated by Django 4.0.3 on 2024-09-01 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SalesLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
                ('sales_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.saleslocation')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weather', models.CharField(max_length=50)),
                ('t_name', models.CharField(max_length=255)),
                ('sales_quantity', models.IntegerField()),
                ('total_sales_quantity', models.IntegerField()),
                ('remaining_number', models.IntegerField()),
                ('total_remaining_number', models.IntegerField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_tally', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_rice_number', models.IntegerField()),
                ('total_no_rice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
                ('sales_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.saleslocation')),
            ],
        ),
    ]
