# Generated by Django 5.1.1 on 2024-09-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='container_type',
            field=models.CharField(default='黒容器', max_length=255),
        ),
    ]
