# Generated by Django 5.1.1 on 2024-09-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_product_container_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
