# Generated by Django 5.1.1 on 2024-09-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_product_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslocation',
            name='direct_return',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleslocation',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
