# Generated by Django 5.1.1 on 2024-09-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_saleslocation_direct_return_saleslocation_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemquantity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='itemquantity',
            name='product',
        ),
        migrations.AddField(
            model_name='itemquantity',
            name='product_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemquantity',
            name='target_date',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AddField(
            model_name='itemquantity',
            name='target_week',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AlterField(
            model_name='itemquantity',
            name='sales_location',
            field=models.CharField(max_length=255),
        ),
    ]
