# Generated by Django 5.1.1 on 2024-09-07 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_itemquantity_date_remove_itemquantity_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemquantity',
            name='sales_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.saleslocation'),
        ),
    ]
