# Generated by Django 5.1.1 on 2024-09-07 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_itemquantity_sales_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemquantity',
            name='product_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product'),
        ),
    ]
