# Generated by Django 5.1.1 on 2024-09-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_rename_product_no_itemquantity_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='no',
            field=models.CharField(max_length=10),
        ),
    ]
