# Generated by Django 5.1.1 on 2024-09-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_product_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
