# Generated by Django 5.1.1 on 2024-09-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_product_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemquantity',
            name='target_date',
            field=models.CharField(default='00000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemquantity',
            name='target_week',
            field=models.CharField(default='00000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='week',
            field=models.CharField(max_length=10),
        ),
    ]
