# Generated by Django 5.1.1 on 2024-09-15 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_itemquantity_target_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('person_in_charge', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=50)),
                ('temp', models.CharField(max_length=50)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paypay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('digital_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sales_difference', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('sold_out_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('food_count_setting', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.saleslocation')),
            ],
        ),
        migrations.DeleteModel(
            name='DailyReportEntry',
        ),
    ]
