# Generated by Django 5.1.1 on 2024-09-15 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_dailyreport_delete_dailyreportentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sales_quantity', models.IntegerField()),
                ('remaining_number', models.IntegerField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_out', models.BooleanField(default=False)),
                ('popular', models.BooleanField(default=False)),
                ('unpopular', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sales.dailyreport')),
            ],
        ),
    ]
