# Generated by Django 5.1.1 on 2024-09-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_dailyreportentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportentry',
            name='product',
            field=models.CharField(max_length=255),
        ),
    ]
