# Generated by Django 5.1.1 on 2024-09-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_dailyreportentry_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='total_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_sales',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
