# Generated by Django 5.1.1 on 2024-09-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_rename_total_sales_dailyreport_total_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='cash',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='digital_payment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='sales_difference',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
