# Generated by Django 5.1.1 on 2024-09-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_dailyreport_cash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='paypay',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyreportentry',
            name='total_sales',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
