# Generated by Django 5.1.1 on 2024-09-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_dailyreport_total_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='total_remaining',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
