# Generated by Django 5.1.1 on 2024-09-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_dailyreport_total_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
