# Generated by Django 5.1.1 on 2024-09-16 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_alter_dailyreport_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.saleslocation'),
        ),
    ]
