# Generated by Django 5.1.1 on 2024-09-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_alter_dailyreport_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
