# Generated by Django 5.1.1 on 2024-09-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_alter_dailyreport_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='cash',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='digital_payment',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='paypay',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10),
        ),
    ]
