# Generated by Django 5.1.1 on 2024-09-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_dailyreport_updated_at_alter_dailyreport_cash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_A',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_B',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_C',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleslocation',
            name='service_name',
            field=models.CharField(default='なし', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleslocation',
            name='service_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
