# Generated by Django 5.1.1 on 2024-09-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_remove_product_price_product_price_a_product_price_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslocation',
            name='price_type',
            field=models.CharField(default='A', max_length=100),
            preserve_default=False,
        ),
    ]
