# Generated by Django 5.1.1 on 2024-09-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_saleslocation_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslocation',
            name='price_type',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
