# Generated by Django 5.1.1 on 2024-09-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_alter_saleslocation_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslocation',
            name='price_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='saleslocation',
            name='service_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
