# Generated by Django 5.1.1 on 2024-10-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_dailyreport_coupon_type_600_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='service_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='service_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='service_type_100',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='service_type_600',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='service_type_700',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
