# Generated by Django 5.1.1 on 2024-10-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_dailyreport_service_name_dailyreport_service_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='gasolin',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='highway',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='others',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='others_price1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='others_price2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='others_sales_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='others_sales_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='others_sales_quantity1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='others_sales_quantity2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='parking',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='part',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
