# Generated by Django 5.1.1 on 2024-10-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_dailyreport_gasolin_dailyreport_highway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='total_others_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
