# Generated by Django 5.1.1 on 2024-11-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
