# Generated by Django 5.1.1 on 2024-11-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_alter_dailyreport_person_in_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='large_rice_quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='large_rice_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
