# Generated by Django 5.1.1 on 2024-11-21 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_dailyreport_large_rice_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='large_rice_quantity',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='large_rice_sales',
        ),
    ]
