# Generated by Django 5.1.1 on 2025-01-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_remove_dailyreport_large_rice_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='others_sales_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='others_sales_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
