# Generated by Django 5.1.1 on 2025-01-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_alter_dailyreport_others_sales_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
