# Generated by Django 5.1.1 on 2025-01-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_dailyreport_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportentry',
            name='product_no',
            field=models.IntegerField(default=0),
        ),
    ]
