# Generated by Django 5.1.1 on 2025-02-09 08:38

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_shiftsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='shiftrequest',
            unique_together={('user', 'date')},
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='status',
            field=models.CharField(choices=[('work', '出勤'), ('off', 'お休み希望')], max_length=10),
        ),
        migrations.DeleteModel(
            name='ShiftSubmission',
        ),
        migrations.RemoveField(
            model_name='shiftrequest',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='shiftrequest',
            name='start_time',
        ),
    ]
