# Generated by Django 5.1.1 on 2025-02-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_holiday_alter_shiftrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='is_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='shiftrequest',
            name='status',
        ),
    ]
