# Generated by Django 5.1.1 on 2025-02-09 09:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_alter_shiftrequest_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftrequest',
            unique_together={('user', 'date')},
        ),
    ]
