# Generated by Django 5.1.1 on 2025-02-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_alter_shiftrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrequest',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
