# Generated by Django 5.1.1 on 2025-02-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_shiftrequest_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrequest',
            name='is_off',
            field=models.CharField(default='', max_length=255),
        ),
    ]
