# Generated by Django 5.1.1 on 2025-02-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0050_alter_shiftrequest_is_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrequest',
            name='is_off',
            field=models.BooleanField(default=False),
        ),
    ]
