# Generated by Django 5.1.1 on 2025-03-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0051_alter_shiftrequest_is_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='sales_price_quantity_1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='sales_price_quantity_2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='sales_price_quantity_3',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
