# Generated by Django 5.1.1 on 2025-05-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0052_dailyreport_sales_price_quantity_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslocation',
            name='service_style',
            field=models.CharField(default='', max_length=100),
        ),
    ]
