# Generated by Django 5.1.1 on 2025-05-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0053_saleslocation_service_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslocation',
            name='service_style',
            field=models.CharField(default='なし', max_length=100),
        ),
    ]
