# Generated by Django 5.1.1 on 2026-02-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0054_alter_saleslocation_service_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslocation',
            name='priority',
            field=models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B')], default='A', max_length=1, verbose_name='優先度'),
        ),
        migrations.AddField(
            model_name='saleslocation',
            name='requires_drive',
            field=models.BooleanField(default=False, verbose_name='運転必須'),
        ),
    ]
