# Generated by Django 5.1.1 on 2026-02-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0055_saleslocation_priority_saleslocation_requires_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslocation',
            name='excluded_from_shift',
            field=models.BooleanField(default=False, verbose_name='シフト対象外'),
        ),
    ]
