# Generated by Django 5.1.1 on 2026-02-23 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0058_init_user_menu_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpoolRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ルート名')),
                ('departure_time', models.TimeField(verbose_name='出発時間')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': '同乗ルート',
                'verbose_name_plural': '同乗ルート',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='saleslocation',
            name='carpool_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='sales.carpoolroute', verbose_name='同乗ルート'),
        ),
    ]
