# Generated by Django 5.1.1 on 2026-03-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0059_carpoolroute_saleslocation_carpool_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenupermission',
            name='direct_return',
            field=models.BooleanField(default=False, verbose_name='直行直帰'),
        ),
    ]
