# Generated by Django 5.1.1 on 2026-03-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0060_usermenupermission_direct_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenupermission',
            name='can_view_direct_return_attendance',
            field=models.BooleanField(default=False, verbose_name='直行直帰出勤記録'),
        ),
    ]
