# Generated by Django 5.1.1 on 2026-03-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0061_usermenupermission_can_view_direct_return_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenupermission',
            name='shin_yokohama',
            field=models.BooleanField(default=False, verbose_name='新横浜'),
        ),
    ]
