# Generated by Django 5.1.1 on 2026-03-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0062_usermenupermission_shin_yokohama'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenupermission',
            name='can_view_orders',
            field=models.BooleanField(default=False, verbose_name='受注管理'),
        ),
    ]
