# Generated by Django 5.1.1 on 2026-03-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0063_usermenupermission_can_view_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenupermission',
            name='can_view_dashboard',
            field=models.BooleanField(default=False, verbose_name='売上ダッシュボード'),
        ),
    ]
