# Generated by Django 5.1.1 on 2026-04-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0064_usermenupermission_can_view_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenupermission',
            name='can_view_quest',
            field=models.BooleanField(default=False, verbose_name='ランチクエスト'),
        ),
    ]
