# Generated by Django 5.1.1 on 2026-04-17 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_submitted_by(apps, schema_editor):
    DailyReport = apps.get_model('sales', 'DailyReport')
    CustomUser = apps.get_model('sales', 'CustomUser')
    for report in DailyReport.objects.filter(submitted_by__isnull=True, person_in_charge__isnull=False):
        name = report.person_in_charge.strip()
        if not name:
            continue
        parts = name.split()
        user = None
        if len(parts) >= 2:
            user = CustomUser.objects.filter(last_name=parts[0], first_name=parts[1]).first()
        if user:
            report.submitted_by = user
            report.save(update_fields=['submitted_by'])


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0066_cleanup_and_unique_dailyreportentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_submitted_by, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ReportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('admin', '管理者'), ('employee', 'スタッフ')], max_length=10)),
                ('field_target', models.CharField(choices=[('comments', 'コメント'), ('food_count_setting', '明日の食数設定')], default='comments', max_length=30)),
                ('message_type', models.CharField(choices=[('text', 'テキスト'), ('reaction', 'リアクション')], default='text', max_length=10)),
                ('body', models.TextField(blank=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='sales.reportmessage')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sales.dailyreport')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_report_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'レポートメッセージ',
                'verbose_name_plural': 'レポートメッセージ',
                'ordering': ['created_at'],
            },
        ),
    ]
