# Generated by Django 5.1.1 on 2026-04-22 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0067_report_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'テキスト'), ('reaction', 'リアクション'), ('stamp', 'スタンプ')], default='text', max_length=10),
        ),
        migrations.CreateModel(
            name='CustomStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='スタンプ名')),
                ('image_data', models.TextField(verbose_name='画像データ(base64 data URI)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_stamps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'カスタムスタンプ',
                'verbose_name_plural': 'カスタムスタンプ',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='reportmessage',
            name='stamp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='sales.customstamp'),
        ),
    ]
