# Generated by Django 5.1.1 on 2026-04-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0068_alter_reportmessage_message_type_customstamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslocation',
            name='accepts_digital_payment',
            field=models.BooleanField(default=False, verbose_name='電子決済対応'),
        ),
    ]
