# Generated by Django 5.1.1 on 2026-05-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0069_saleslocation_accepts_digital_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslocation',
            name='excluded_from_public_status',
            field=models.BooleanField(default=False, help_text='お客様向け公開ページ（status.lunchnetsalessystem.com）に出さない拠点。配達など、社内シフトには残すが対外的に出店ではないもの。', verbose_name='出店状況ページ非表示'),
        ),
    ]
