# Generated by Django 5.1.1 on 2026-07-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0075_stamp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenupermission',
            name='can_view_stamp',
            field=models.BooleanField(default=False, verbose_name='公式LINE（スタンプ）'),
        ),
    ]
