# Generated by Django 5.1.1 on 2026-07-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0076_usermenupermission_can_view_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslocation',
            name='expects_cash',
            field=models.BooleanField(default=True, help_text='OFF の拠点（社員食堂・配達など現金を扱わない売り場）は、日計表の現金欄をグレーアウトし、未入力チェックの対象外にする。', verbose_name='現金入力あり'),
        ),
    ]
