# Generated by Django 5.1.1 on 2026-07-05 00:05

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def check_no_duplicates(apps, schema_editor):
    """制約を張る前に、同日・同売場の重複が残っていないか確認する。
    残っている場合はデプロイを止めて、手動で該当行を掃除するよう明示する
    （生の IntegrityError より原因が分かるようにするための防御）。"""
    DailyReport = apps.get_model('sales', 'DailyReport')
    dups = (
        DailyReport.objects.values('date', 'location')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
    )
    if dups:
        detail = ', '.join(f"{d['date']}／{d['location']}（{d['c']}件）" for d in dups)
        raise RuntimeError(
            "日計表に同日・同売場の重複が残っています。ユニーク制約を張れません。"
            "先に重複行を1件に整理してから再デプロイしてください → " + detail
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0077_saleslocation_expects_cash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(check_no_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(fields=('date', 'location'), name='uniq_dailyreport_date_location'),
        ),
    ]
