# Generated by Django 5.1.1 on 2026-10-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0078_dailyreport_uniq_dailyreport_date_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemQuantityUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('api', '振分表の確定ボタン'), ('screen', '画面アップロード')], max_length=10)),
                ('ok', models.BooleanField(default=False)),
                ('saved_count', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
    ]
