# Generated by Django 5.1.1 on 2026-10-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0079_itemquantityupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecastSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('target_date', models.DateField(db_index=True)),
                ('lunch_precip', models.FloatField()),
                ('lunch_snow', models.FloatField(default=0)),
                ('lunch_temp', models.FloatField(blank=True, null=True)),
                ('lunch_feels', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
