# Generated by Django 5.1.1 on 2026-10-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0080_weatherforecastsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='coupon_type_750',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
