# Generated by Django 5.1.1 on 2026-10-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0081_dailyreport_coupon_type_750'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='service_type_750',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
