# Generated by Django 5.1.1 on 2026-10-07 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0082_dailyreport_service_type_750'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='値段の種類')),
                ('is_bento', models.BooleanField(default=True, verbose_name='弁当')),
                ('sort_order', models.IntegerField(default=0, verbose_name='並び順')),
            ],
            options={
                'verbose_name': '値段の種類',
                'verbose_name_plural': '値段の種類',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='dailyreportentry',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='DiscountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('rice', 'ご飯'), ('refund', '割引・返金')], max_length=10)),
                ('label', models.CharField(max_length=50, verbose_name='表示名')),
                ('direction', models.CharField(choices=[('minus', '引く'), ('plus', '足す')], max_length=5)),
                ('amount', models.PositiveIntegerField(verbose_name='金額')),
                ('sort_order', models.IntegerField(default=0)),
                ('valid_from', models.DateField(verbose_name='開始日')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('legacy_field', models.CharField(blank=True, max_length=50)),
                ('csv_label', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '割引項目',
                'verbose_name_plural': '割引項目',
                'ordering': ['group', 'sort_order', 'valid_from'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='sales.pricerank', verbose_name='値段の種類'),
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(unique=True, verbose_name='開始日')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '価格表',
                'verbose_name_plural': '価格表',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='DailyReportDiscountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('rice', 'ご飯'), ('refund', '割引・返金'), ('coupon', 'クーポン'), ('service', 'サービス販売')], max_length=10)),
                ('label', models.CharField(max_length=50)),
                ('base_price', models.IntegerField(default=0)),
                ('unit_amount', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_lines', to='sales.dailyreport')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='sales.discountitem')),
            ],
            options={
                'ordering': ['report', 'group', '-base_price', 'id'],
                'constraints': [models.UniqueConstraint(fields=('report', 'group', 'label'), name='uniq_discountline_report_group_label')],
            },
        ),
        migrations.CreateModel(
            name='PriceTableCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(choices=[('A', '価格A'), ('B', '価格B'), ('C', '価格C')], max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cells', to='sales.pricerank')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='sales.pricetable')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('table', 'rank', 'pattern'), name='uniq_pricecell_table_rank_pattern')],
            },
        ),
    ]
