# Generated by Django 5.1.1 on 2026-10-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0084_price_master_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermenupermission',
            name='can_view_price_master',
            field=models.BooleanField(default=False, verbose_name='価格・メニュー設定'),
        ),
    ]
