# Generated by Django 5.1.1 on 2026-10-08 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0086_price_change_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, verbose_name='メニュー名にこの言葉があれば')),
                ('container', models.CharField(blank=True, max_length=20, verbose_name='容器')),
                ('sort_order', models.IntegerField(default=0)),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.pricerank', verbose_name='値段の種類')),
            ],
            options={
                'verbose_name': '判定ルール',
                'verbose_name_plural': '判定ルール',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='メニュー名')),
                ('container', models.CharField(max_length=20, verbose_name='容器')),
                ('confirmed', models.BooleanField(default=False, verbose_name='確認済み')),
                ('first_seen', models.DateField(blank=True, null=True, verbose_name='初めて出た週')),
                ('last_seen', models.DateField(blank=True, null=True, verbose_name='最後に出た週')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_profiles', to='sales.pricerank', verbose_name='値段の種類')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'メニューデータベース',
                'verbose_name_plural': 'メニューデータベース',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuWeekCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(unique=True, verbose_name='週（水曜）')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='届いた日時')),
                ('received_count', models.IntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='確認した日時')),
                ('resent_after_confirm', models.BooleanField(default=False)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '週のメニュー確認',
                'verbose_name_plural': '週のメニュー確認',
                'ordering': ['-week'],
            },
        ),
    ]
