# Generated by Django 5.1.1 on 2026-10-08 09:17

from django.db import migrations, models

# 横浜の売場は、都心（新橋）と昼の雨の予報が違う日が多いので地点を分ける
AREAS = {"日本大通り": "yokohama", "新山下": "yokohama", "本町一丁目": "yokohama", "新横浜": "shinyokohama"}


def set_areas(apps, schema_editor):
    SalesLocation = apps.get_model("sales", "SalesLocation")
    for name, area in AREAS.items():
        SalesLocation.objects.filter(name=name).update(weather_area=area)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0088_menu_dictionary_initial_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslocation',
            name='weather_area',
            field=models.CharField(choices=[('tokyo', '東京'), ('yokohama', '横浜みなと'), ('shinyokohama', '新横浜')], default='tokyo', help_text='食数予測の雨の補正に使う天気予報の地点。横浜は都心と予報が違う日が多い。', max_length=20, verbose_name='天気の地点'),
        ),
        migrations.AddField(
            model_name='weatherforecastsnapshot',
            name='area',
            field=models.CharField(default='tokyo', max_length=20),
        ),
        migrations.RunPython(set_areas, migrations.RunPython.noop),
    ]
